name: Feature request
description: Suggest an idea or improvement
title: '[Feature]: '
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for your request.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: summary
    attributes:
      label: Feature summary
      description: A clear and concise summary of the feature.
      placeholder: 'I want to be able to...'
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you want this feature? What problem does it solve?
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution or design
      description: If you have ideas about how this could be implemented, share them here.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Did you consider any alternative solutions or features?
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or references here.
